name: Scheduled PDF Upload

on:
  schedule:
    - cron: '1 0 5 3 *'  # Runs at 12:01 AM on March 5, 2025 (UTC time)

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Apply Stashed Changes
        run: |
          git config --global user.name "ilb225112"
          git config --global user.email "ilb225112@gmail.com"
          git stash pop
          git add cn/lab/LAB_04_03/PES1UG23CS167_3_CHIRAG_KM.pdf
          git commit -m "Scheduled upload of solution PDF"
          git push

